// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecondHandCarDemoRepo;

#nullable disable

namespace SecondHandCarDemoRepo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SecondHandCarDemoRepo.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Kilometer")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Maruti Suzuki",
                            Kilometer = 13450L,
                            Model = "Swift",
                            Price = 350000L
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Honda",
                            Kilometer = 23987L,
                            Model = "City",
                            Price = 750000L
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Mahindra",
                            Kilometer = 43006L,
                            Model = "Thar",
                            Price = 1000000L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
